############################################################
# mybatis 配置
############################################################
mybatis:
  type-aliases-package: com.fr.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############################################################
#数据库连接配置
############################################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://cdb-67p38xpq.cd.tencentcdb.com:10004/frecognition?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456root

############################################################
# mybatis mapper 配置
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.fr.my.mapper.MyMapper
  not-empty: false    # 在进行数据库操作的的时候，判断表达式 username != null, 是否追加 username != ''
  identity: MYSQL


###################以下为FastDfs的配置###########################
fdfs:
  so-timeout: 2500
  connect-timeout: 1000
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 47.106.182.155:22122
upload:
  base-url: http://47.106.182.155:8888/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpeg